---
abstract: 'read and write xlogfiles'
author:
  - 'Shawn M Moore, C<sartak@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Temp: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-XLogfile
no_index:
  directory:
    - inc
    - t
resources:
  homepage: http://github.com/sartak/Text-XLogfile/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sartak/Text-XLogfile.git
version: 0.05
